export enum PAYMENT_STATUS {
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELED = "CANCELED",
    REFUNDED = "REFUNDED",
}

export enum PAYMENT_ITEM_TYPE {
    SUBSCRIPTION = "SUBSCRIPTION",
    SLOT_PACKAGE = "SLOT_PACKAGE",
    DONATION = "DONATION"
}